# This workflow is to be used in other worklfows, like main and release
name: Deploy

on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
      deployment-role:
        type: string
        required: true
      AWS_REGION:
        required: false
        default: eu-central-1
        type: string
      skip_infra:
        description: "Skip infrastructure deployment"
        type: boolean
        default: false
        required: true

env:
  NODE_VERSION: "20.x"
  AWS_REGION: ${{ inputs.AWS_REGION }}

jobs:
  deploy:
    name: "Deploy to ${{ inputs.env }}"
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
          driver-opts: |
            image=moby/buildkit:latest

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile', 'package.json') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.deployment-role }}
          aws-region: ${{ inputs.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install deps
        run: make install-deps

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./Docker
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/skyflow-dji-stream-server:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          provenance: false
          outputs: type=docker

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Deploy Infrastructure
        if: ${{ !inputs.skip_infra }}
        run: make deploy-infra

      - name: Force new deployment of the ECS service
        run: make force-deploy
